// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-4TMVmAA-aUQx1K0fK8n1rilaJRhM-Q',
    appId: '1:542400573545:web:ac59fd4bb5c46814ba32f8',
    messagingSenderId: '542400573545',
    projectId: 'gift-of-the-thistle',
    authDomain: 'gift-of-the-thistle.firebaseapp.com',
    storageBucket: 'gift-of-the-thistle.appspot.com',
    measurementId: 'G-TZJF6KEVDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BgVQwxXXwtSGKA4F9HzcmoeYBsDXOX0',
    appId: '1:542400573545:android:45d5db8d7c6c2ac5ba32f8',
    messagingSenderId: '542400573545',
    projectId: 'gift-of-the-thistle',
    storageBucket: 'gift-of-the-thistle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_71qsHzOvXIu323ofIlvcgsvRa8ad0Lk',
    appId: '1:542400573545:ios:17a52be904a747ceba32f8',
    messagingSenderId: '542400573545',
    projectId: 'gift-of-the-thistle',
    storageBucket: 'gift-of-the-thistle.appspot.com',
    iosBundleId: 'com.thistle.thistle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_71qsHzOvXIu323ofIlvcgsvRa8ad0Lk',
    appId: '1:542400573545:ios:17a52be904a747ceba32f8',
    messagingSenderId: '542400573545',
    projectId: 'gift-of-the-thistle',
    storageBucket: 'gift-of-the-thistle.appspot.com',
    iosBundleId: 'com.thistle.thistle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL-4TMVmAA-aUQx1K0fK8n1rilaJRhM-Q',
    appId: '1:542400573545:web:1d19eb1efef87fa0ba32f8',
    messagingSenderId: '542400573545',
    projectId: 'gift-of-the-thistle',
    authDomain: 'gift-of-the-thistle.firebaseapp.com',
    storageBucket: 'gift-of-the-thistle.appspot.com',
    measurementId: 'G-KC7TELCNQZ',
  );
}
